### PR TITLE
COM-965 - Put everything tf-related in terraform folder

### PR DESCRIPTION
**Pull request by francoislg**
[COM-965]

Yes, this is my third attempt at a terraform folder structure

The issue that I have in prod is this:

> [REDACTED] Call to function "find_in_parent_folders" failed: Could not find a Terragrunt config file in any of the parent folders of [REDACTED]/.terragrunt.hcl., and 1 other diagnostic(s)

So what I am guessing is that the deployment pipeline only fetches the `terraform` folder and nothing else at the root, and it executes `tgf plan-all` in the `terraform` folder.

So here, I put all the TGF-related files in the `terraform` folder, ran `tgf plan-all` from it, and I have a proper plan. 

It should work this time :trynottocryparrot:

[COM-965]: https://coveord.atlassian.net/browse/COM-965

### CODE REVIEW

**Review by dlafreniere — APPROVED** [review]
cloudfront is a distinct TF module?

**Comment by francoislg** [comment]
> cloudfront is a distinct TF module?

I didn't really know how to name it, it seemed to work when `tgf plan-all`-ing

**Comment by francoislg** [comment]
shit you are right:

>  Running terragrunt on /current_sources/flguillemette/Documents/repos/coveo.analytics.js/terraform/cloudfront

I'll rename it

**Review by toussaints — APPROVED** [review]

**Comment by francoislg** [comment]
```
14:44:08  Error: No value for required variable
14:44:08  
14:44:08    on invalidate-cloudfront.tf line 1:
14:44:08     1: variable "package_json_major_version" {
```

:soclose:

**Pull request merged**
